[project]
name = "code-complete"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "openai>=3.1.0",
    "python-dotenv>=1.2.3",
    "tenacity>=9.1.4",
]

[project.optional-dependencies]
dev = ["pytest", "pytest-asyncio"]

[tool.pytest.ini_options]
asyncio_mode = "auto"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ruff>=0.16.3",
]

[tool.hatch.build.targets.wheel]
packages = ["agent"]

[tool.ruff]
indent-width = 2

[tool.ruff.lint]
select = ["E", "F", "I"]

[tool.ruff.format]
indent-style = "space"
